language: python
sudo: false
python:
  - 3.6
  - 2.7

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --verbose --cover-package=clusterpy;
  #- cd doc; make pickle; make doctest
notifications:
    email:
        recipients:
            - levi.john.wolf@gmail.com
        on_failure: always
        on_change: always
